In [2]:
import pandas as pd
import sqlite3

In [3]:
# monta o google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
conn = sqlite3.connect('/content/drive/MyDrive/data_japan.db')
cur = conn.cursor()

In [31]:
# Carregar planilhas
from google.colab import files
uploaded = files.upload()

Saving nationality by prefecture 2024 data(Sheet2).csv to nationality by prefecture 2024 data(Sheet2).csv

In [32]:
# pandas tables
df_immi_entrance = pd.read_csv('entrance in japan - nationalities_year.csv')
df_foreigner_country = pd.read_csv('Foreigners Residing in Japan by Nationality and Region by Status of Residence 2024 data(Country).csv')
df_nat_by_pref = pd.read_csv('nationality by prefecture 2024 data(Sheet2).csv')
df_pref_by_nat = pd.read_csv('nationality by prefecture 2024 data(in).csv')

In [33]:
# sql tables
df_immi_entrance.to_sql('immi_entrance', conn, if_exists='replace', index=False)
df_foreigner_country.to_sql('foreigner_country', conn, if_exists='replace', index=False)
df_nat_by_pref.to_sql('nat_by_pref', conn, if_exists='replace', index=False)
df_pref_by_nat.to_sql('pref_by_nat', conn, if_exists='replace', index=False)

48

## Immigration by Prefecture
#### 2023/24 Data

1. What are the top 10 immigrant nationalities by entry type in Japan in 2023

In [13]:
pd.read_sql('''
                SELECT *
                FROM immi_entrance
                WHERE year = 2023
                ORDER BY total DESC
                LIMIT 10;
                ''', conn)

,year,country,total,diplomacy,government business,professor,art,religion,news_report,Investment,...,studying_abroad,training,family_stay,specific_activities,permanent_resident,spouses_of_japanese_other,spouses_permanent_residents,settlers,special_permanent_resident,Special Permanent Resident
0,2023,Korea,7144615,1090,2216,2389,182,1721,99,None,...,6783275,36870,64,16816,5892,100764,19743,3887,8039,68306
1,2023,Taiwan,4173929,6,5,604,32,221,8,None,...,4059289,16161,32,5344,4501,35707,7890,758,1809,358
2,2023,China,2678102,606,3694,2676,149,67,48,None,...,883534,163895,159,65890,8073,276810,22796,16294,20395,70
3,2023,United States,2082697,2641,3470,1759,266,1444,77,None,...,1984423,9179,4,7516,391,20906,14070,505,1445,900
4,2023,China [Hong Kong],2049954,5,40,93,22,125,1,None,...,2026082,5256,2,2444,1104,3417,1632,179,230,11
5,2023,Thailand,1020690,319,4539,374,6,191,0,None,...,15208,6100,576,949,349,15345,6874,532,2488,2
6,2023,Philippines,734011,349,1790,224,0,413,0,None,...,347876,2970,423,3694,3502,72896,16849,3368,27224,7
7,2023,Australia,620480,314,402,256,22,100,19,None,...,600561,1125,6,1370,2505,4611,2603,117,126,136
8,2023,Vietnam,602337,662,2420,321,1,216,4,None,...,26458,36331,565,42872,10848,18147,6919,2023,4659,2
9,2023,Singapore,593997,91,43,64,14,81,4,None,...,586581,839,2,483,54,1800,849,38,59,15

2. What are the most common status of residence for each nationalities?
How are these groups distributed across the country's prefectures?

Displayed in an interactive Dashboard in [Tableau](https://public.tableau.com/app/profile/gabriela.yoshizaki/viz/NationalitiesinJapanbyPrefectureandStatusofResidence/Dashboard1)

3.  What are the top 5 immigrant nationalities residing in Japan?

In [40]:
pd.read_sql('''
                SELECT Prefecture as Country, total
                FROM nat_by_pref
                ORDER BY total DESC
                LIMIT 6;
                ''', conn)

       Country    Total
0        Total  3588956
1        China   844187
2     Viet Nam   600348
3  South Korea   411043
4  Philippines   332293
5       Brazil   212325

3. How are these nationalities distributed across the country's prefectures?

In [45]:
df_pref_by_nat.head()

,Prefecture,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,...,United Kingdom,Uruguay,USA,Uzbekistan,Vanuatu,Venezuela,Viet Nam,Yemen,Zambia,Zimbabwe
0,Hokkaido,162,0,1,0,3,1,64,1,728,...,638,3,1520,91,0,37,13287,0,40,53
1,Aomori,28,0,0,0,0,0,5,0,20,...,35,0,405,0,0,0,2381,0,0,0
2,Iwate,10,0,2,0,0,0,1,0,45,...,96,0,220,13,0,3,2763,0,0,1
3,Miyagi,40,1,3,0,0,0,13,0,105,...,145,0,717,5,0,6,4977,1,7,7
4,Akita,20,0,0,0,0,0,1,0,33,...,48,0,224,15,0,0,1023,0,0,6

In [49]:
# top 5 Nationalities in Japan by Prefecture

pd.read_sql('''
                SELECT Prefecture,
                       China,
                       "South Korea",
                       "Viet Nam",
                       Philippines,
                       Brazil
                FROM pref_by_nat
                ''', conn)

           Prefecture   China  South Korea  Viet Nam  Philippines  Brazil
0            Hokkaido    9824         4414     13287         3342     181
1              Aomori     983          676      2381          911      35
2               Iwate    1544          690      2763         1548     107
3              Miyagi    5563         2982      4977         1747     159
4               Akita     947          480      1023          979      12
5            Yamagata    1883         1370      2991         1040      88
6           Fukushima    3086         1270      4707         3014     215
7             Ibaraki   12532         4031     19279        11631    6068
8             Tochigi    6328         2193     11206         5511    3996
9               Gunma    6603         2041     15222         9395   13829
10            Saitama   81800        15621     44300        24658    7415
11              Chiba   59619        15625     35458        22500    3617
12              Tokyo  272328        92121     50301        36948    4391
13           Kanagawa   78979        27490     37867        26826    9474
14            Niigata    4453         1575      4807         3174     305
15             Toyama    4360          782      5758         2852    2541
16           Ishikawa    3915         1174      5548         1594    1716
17              Fukui    1987         1783      3873         2221    4780
18          Yamanashi    4458         1641      4428         2386    2782
19             Nagano    8456         3069      7136         5488    4858
20               Gifu    9300         3154     14598        15908   12302
21           Shizuoka   10360         4244     19133        20251   32526
22              Aichi   46122        26289     61045        45852   61305
23                Mie    6451         3735     13791         8553   13967
24              Shiga    4745         3699     10434         3277    9618
25              Kyoto   18954        20811     10118         3119     603
26              Osaka   81499        87808     58529        11835    2776
27              Hyogo   23762        34827     30342         6515    2409
28               Nara    3093         3046      4222         1053     329
29           Wakayama    1331         1766      2051          945     113
30            Tottori     730          792      1607          730      35
31            Shimane    1083          536      1746         1111    3838
32            Okayama    6967         4170     12012         2530     938
33          Hiroshima   12141         6450     15308        10194    2319
34          Yamaguchi    2392         4363      4890         2112     309
35          Tokushima    1613          293      2288          941      40
36             Kagawa    3066          777      4328         2750     180
37              Ehime    2617         1047      4517         3780     244
38              Kochi     937          429      1495          898      24
39            Fukuoka   20998        14493     21884         6891     414
40               Saga    1007          574      2875          897      33
41           Nagasaki    2072         1062      3004         1650      64
42           Kumamoto    3394         1047      6779         3952      78
43               Oita    2277         1636      3672         1999      82
44           Miyazaki     877          489      2914         1019      57
45          Kagoshima    1705          494      5520         2548     114
46            Okinawa    2969         1484      2659         2673     921
47  Undecided/Unknown    2077          500      1275          545     118